#!/bin/bash
 
# get the root directory for the repository
RootDir=`git rev-parse --show-toplevel`
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
# get all the files that are staged
for v in `git diff --name-only --cached`
do
    # if it is java file
    if [[ ${v} == *.java ]]
    then
        echo "format" ${v} "in google-java-format style"
        java -jar ${DIR}/google-java-format.jar -r -a "$RootDir/$v"
        git add "$RootDir/$v"
    fi
    # if it is javascript file
    if [[ ${v} == *.js ]]
    then
        js-beautify -r -n -j "$RootDir/$v"
        git add "$RootDir/$v"
    fi
done
 
exit 0